source 'https://rubygems.org'

gem 'rails'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'pg'
gem 'dotenv-rails'
gem 'faraday'
gem 'faraday_middleware'
gem 'slim'
gem 'thin'
gem 'bootstrap-sass'
gem 'compass-rails'
gem 'omniauth-oauth2'

group :development, :test do
  gem 'sqlite3'
  gem 'binding_of_caller'
  gem 'better_errors'
  gem 'awesome_print'
  gem 'guard-livereload'
end
